"""empty message

Revision ID: 2bb6eb0c5af2
Revises: 
Create Date: 2017-04-13 06:41:42.292000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bb6eb0c5af2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ops_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['ops_departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ops_idcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ops_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('default', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ops_roles_default'), 'ops_roles', ['default'], unique=False)
    op.create_table('ops_software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_software_name'), 'ops_software', ['name'], unique=True)
    op.create_index(op.f('ix_ops_software_version'), 'ops_software', ['version'], unique=True)
    op.create_table('ops_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('mobile', sa.INTEGER(), nullable=True),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.Text(), nullable=True),
    sa.Column('member_since', sa.DateTime(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('allow_login', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['ops_roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ops_users_allow_login'), 'ops_users', ['allow_login'], unique=False)
    op.create_index(op.f('ix_ops_users_department'), 'ops_users', ['department'], unique=False)
    op.create_index(op.f('ix_ops_users_email'), 'ops_users', ['email'], unique=False)
    op.create_index(op.f('ix_ops_users_mobile'), 'ops_users', ['mobile'], unique=False)
    op.create_index(op.f('ix_ops_users_username'), 'ops_users', ['username'], unique=True)
    op.create_table('ops_projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('pm_id', sa.Integer(), nullable=True),
    sa.Column('sla', sa.String(length=32), nullable=True),
    sa.Column('check_point', sa.String(length=64), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['pm_id'], ['ops_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ops_projects_department'), 'ops_projects', ['department'], unique=False)
    op.create_table('ops_modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('svn', sa.String(length=128), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('dev_id', sa.Integer(), nullable=True),
    sa.Column('qa_id', sa.Integer(), nullable=True),
    sa.Column('ops_id', sa.Integer(), nullable=True),
    sa.Column('software_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['dev_id'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['ops_id'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['ops_modules.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['ops_projects.id'], ),
    sa.ForeignKeyConstraint(['qa_id'], ['ops_users.id'], ),
    sa.ForeignKeyConstraint(['software_id'], ['ops_software.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_ops_modules_department'), 'ops_modules', ['department'], unique=False)
    op.create_table('ops_environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('env', sa.String(length=32), nullable=True),
    sa.Column('idc', sa.String(length=64), nullable=True),
    sa.Column('check_point1', sa.String(length=128), nullable=True),
    sa.Column('check_point2', sa.String(length=128), nullable=True),
    sa.Column('check_point3', sa.String(length=128), nullable=True),
    sa.Column('deploy_path', sa.String(length=128), nullable=True),
    sa.Column('server_ip', sa.String(length=128), nullable=True),
    sa.Column('online_since', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['ops_modules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ops_environments')
    op.drop_index(op.f('ix_ops_modules_department'), table_name='ops_modules')
    op.drop_table('ops_modules')
    op.drop_index(op.f('ix_ops_projects_department'), table_name='ops_projects')
    op.drop_table('ops_projects')
    op.drop_index(op.f('ix_ops_users_username'), table_name='ops_users')
    op.drop_index(op.f('ix_ops_users_mobile'), table_name='ops_users')
    op.drop_index(op.f('ix_ops_users_email'), table_name='ops_users')
    op.drop_index(op.f('ix_ops_users_department'), table_name='ops_users')
    op.drop_index(op.f('ix_ops_users_allow_login'), table_name='ops_users')
    op.drop_table('ops_users')
    op.drop_index(op.f('ix_ops_software_version'), table_name='ops_software')
    op.drop_index(op.f('ix_ops_software_name'), table_name='ops_software')
    op.drop_table('ops_software')
    op.drop_index(op.f('ix_ops_roles_default'), table_name='ops_roles')
    op.drop_table('ops_roles')
    op.drop_table('ops_idcs')
    op.drop_table('ops_departments')
    # ### end Alembic commands ###
