"""empty message

Revision ID: 505560cc374d
Revises: dc6b7dbb8ed5
Create Date: 2017-03-22 14:09:23.722000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '505560cc374d'
down_revision = 'dc6b7dbb8ed5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('software',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('software')
    # ### end Alembic commands ###
