"""empty message

Revision ID: 92ec2b17f570
Revises: ae45e90b0bf7
Create Date: 2017-03-30 17:15:33.023000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92ec2b17f570'
down_revision = 'ae45e90b0bf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('module_id', sa.Integer(), nullable=True),
    sa.Column('idc', sa.String(length=64), nullable=True),
    sa.Column('env', sa.String(length=32), nullable=True),
    sa.Column('check_point1', sa.String(length=128), nullable=True),
    sa.Column('check_point2', sa.String(length=128), nullable=True),
    sa.Column('check_point3', sa.String(length=128), nullable=True),
    sa.Column('deploy_path', sa.String(length=128), nullable=True),
    sa.Column('server_ip', sa.String(length=128), nullable=True),
    sa.Column('online_since', sa.DateTime(), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('environments')
    # ### end Alembic commands ###
