"""empty message

Revision ID: c8b66a830690
Revises: f8d7cb9fe8f3
Create Date: 2017-03-16 13:34:21.874000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b66a830690'
down_revision = 'f8d7cb9fe8f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('allow_login', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_users_allow_login'), 'users', ['allow_login'], unique=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_index(op.f('ix_users_allow_login'), table_name='users')
    op.drop_column('users', 'allow_login')
    # ### end Alembic commands ###
